sudo: required
language: ruby
rvm:
  - 2.5.3
services:
  - docker
env:
  - DOCKER_COMPOSE_VERSION=1.22.0 CI=true TRAVIS=true
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - sudo /etc/init.d/postgresql stop
  - docker-compose build
  - gem install bundler
script:
  - echo "GOOGLE_API_KEY=this_is_a_test" >> ./docker/.env.app.conf
  - docker-compose run app bundle
  - docker-compose run app bundle exec rake db:setup INITIAL_ADMIN_EMAIL=joatu-admin@grr.la INITIAL_ADMIN_PASSWORD=password
  - docker-compose run app bundle exec rspec