# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE") %>
  secret_token: <%= ENV.fetch("SECRET_TOKEN") %>

test:
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE") %>
  secret_token: <%= ENV.fetch("SECRET_TOKEN") %>

alpha:
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE") %>
  secret_token: <%= ENV.fetch("SECRET_TOKEN") %>

demo:
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE") %>
  secret_token: <%= ENV.fetch("SECRET_TOKEN") %>

production:
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE") %>
  secret_token: <%= ENV.fetch("SECRET_TOKEN") %>
